apiVersion: v1
kind: Service   
metadata:
  name: app-with-argocd-service
spec:
  selector:
    app.kubernetes.io/name: app-with-argocd-deployment
  type: NodePort
  ports:
  - protocol: TCP
    nodePort: 31080
    port: 8080
    targetPort: 8080