apiVersion: v1
kind: Secret
metadata:
  name: db-secret-info
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: azhzMTIzNDUK
  MYSQL_DATABASE: YXBwCg==
  MYSQL_USER: YXBwCg==
  MYSQL_PASSWORD: YXBwMTIzNDUK